### PR TITLE
RTX handling text 

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by fluffy** [comment]
This is not ready to merge yet but can be used to start discussion on RTX text

**Comment by suhasHere** [comment]
Higher level question .. Should it help having a generic repair processing section that identifies the sender and receiver behavior. It could be informative and can reflect the pictures from the presentation. Thoughts ?

**Comment by nils-ohlmeier** [comment]
I think as confusing as the whole topic is/was to us experts I think we should have a paragraph explaining that any of the repairs are effectively a triple encryption.

**Comment by suhasHere** [comment]
looks good

**Pull request merged**
